### ISSUE TITLE
crashes by testing with "SafetyNet Helper" app

### ISSUE THREAD

**Issue by LatexXx** [microg/RemoteDroidGuard#1]
First I want to thank you for your amazing work.
I just saw the DroidGuard Helper coming up and wanted to give it a try.

Samsung Galaxy S2 (gt-i9100)
cm13.0 nightly20160924
with Xposed

I got the "SafetyNet Helper" app from the PlayStore and started the test, but DroidGuard helper crashed and the test failed.

I saved the log via Catlog, maybe it is helpfull for you.
[2016-09-25-18-45-43.txt](https://github.com/microg/android_packages_apps_RemoteDroidGuard/files/491771/2016-09-25-18-45-43.txt)

**Comment by seanrand** [comment]
You're probably using either DroidGuard Helper 0.1.0-1 or 0.1.0-2 that have an Xposed module integrated. Those were test versions that never really worked, you should either downgrade to 0.1.0 or upgrade to 0.1.0-3.

**Comment by ale5000-git** [comment]
@LatexXx
The version 0.1.0-3 is here: https://microg.org/fdroid/repo/org.microg.gms.droidguard-7.apk

**Comment by ale5000-git** [comment]
Have you tried the latest version?

**Comment by ale5000-git** [comment]
@LatexXx
The version 0.1.0-10 is here: https://microg.org/fdroid/repo/org.microg.gms.droidguard-14.apk

Did the latest version work for you?

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19

(sorry for spamming your inbox)

**Comment by ale5000-git** [comment]
@Nanolx: No problem, in this way I find issues more easily.
