### ISSUE TITLE
couldnt find libarthook_native.so

### ISSUE THREAD

**Issue by ghost** [microg/RemoteDroidGuard#10]
Hi, i got this error when running SaftyNet Helper.
Android 7.1.1
January Security Patch Level
Resurrection Remix OS 5.8.0-20170121-h815-Unofficial_tyler

```
05:06:11.827  7072  7197 E AndroidRuntime: FATAL EXCEPTION: Thread-2
01-28 05:06:11.827  7072  7197 E AndroidRuntime: Process: com.google.android.gms.unstable, PID: 7072
01-28 05:06:11.827  7072  7197 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/org.microg.gms.droidguard.apk"],nativeLibraryDirectories=[/system/lib64/org.microg.gms.droidguard, /system/fake-libs64, /system/priv-app/org.microg.gms.droidguard.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libarthook_native.so"
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at de.larma.arthook.Native.<clinit>(Native.java:22)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at de.larma.arthook.Native.is64Bit(Native.java:45)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at de.larma.arthook.ArtHook.<clinit>(ArtHook.java:46)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at de.larma.arthook.ArtHook.hook(ArtHook.java:75)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at org.microg.gms.droidguard.SysHook.activate(SysHook.java:52)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:91)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
01-28 05:06:11.827  7072  7197 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

kind regards

**Comment by ale5000-git** [comment]
Do you have the latest version?

**Comment by ghost** [comment]
thx, it works now
i dunno how i got the wrong version from f-droid
probably miss clicked, sorry bro

**Comment by jamyy2000** [comment]
How did you solved this problem?I also get the same problem. Thanks.

**Comment by ale5000-git** [comment]
@jamyy2000: Do you have the [latest version](https://microg.org/download.html) of DroidGuard Helper installed (currently 0.1.0-10)?

**Comment by jamyy2000** [comment]
@ale5000-git I didn't install DroidGuard Helper, I just push my APK into /system/priv-app/, and the apk contains some *.so files in /lib/arm64/ path,when run the APK,it cause UnsatisfiedLinkError, the error log is ：
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/TestNative/TestNative.apk"],nativeLibraryDirectories=[/system/priv-app/TestNative/lib/arm64, /system/fake-libs64, /system/priv-app/TestNative/TestNative.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libtest.so" .

**Comment by ale5000-git** [comment]
@jamyy2000: This prove you are using an old version since the latest version no longer use libs.
You should push an updated apk.

**Comment by jamyy2000** [comment]
@ale5000-git:  I'm using new Huawei device,and It didn't install the apk at all, I just develop a apk using jni includes /libs/arm64/xxx.so,and root the device,and push the apk into /system/priv-app/ path,make this apk cann't be uninstalled , but when run the test apk,get the problem.

**Comment by ale5000-git** [comment]
@jamyy2000: You just have to push the new version with the same name and position of the old version in system/priv-app/ and it will overwrite it.

Note: To download the apk go [here](https://microg.org/download.html), in the drop down menu of DroidGuard Helper choose 0.1.0-10.
