### ISSUE TITLE
Support for API 9

### ISSUE THREAD

**Issue by ale5000-git** [microg/RemoteDroidGuard#15]
Please add support for API 9

**Comment by mar-v-in** [comment]
Are there actual devices still running API 9?

**Comment by ale5000-git** [comment]
Well, a phone is working until isn't broken.
It can be almost forever if you are lucky.

There are a lot of used phones that can be bought.

**Comment by mar-v-in** [comment]
Sure, but I think all of them actually upgraded to API 10+

**Comment by ale5000-git** [comment]
It may not happen on all phones, there are a lot of unknown chinese brands that do not give support at all.
