### ISSUE TITLE
Safetynet no longer working

### ISSUE THREAD

**Issue by MattVibes** [microg/RemoteDroidGuard#21]
Hello!
I installed all the latest MicroG components on my oreo phone, everything works... Except one single, very annoying, thing... Whenever I try to test Safetynet with either Magisk or "Safetynet Test" app, "Droidguard Helper has stopped working" and ofc it fails. This means I can't download Netflix or login to Snapchat for example. Does anyone have a workaround as Safetynet is relatively important nowadays.

**Comment by ArchangeGabriel** [comment]
It has been the case for the past 3 months: https://github.com/microg/android_packages_apps_GmsCore/issues/526

**Comment by MattVibes** [comment]
Okay thanks, Nanodroid is the goto option then?

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19
