### ISSUE TITLE
MicroG lineage build don't pass SafetyNet and I'm very new to this

### ISSUE THREAD

**Issue by Atrashraccoon** [microg/RemoteDroidGuard#23]
Hi,

I installed microG for LineageOS on both my S9+ and S7 Edge but even when I enable SafetyNet and installed the Droid Guard Helper from Fdroid I can't pass the test.

I've read that you might need to push files to /system/priv-app/ and other things but I have no idea how to do that and if I should.

**Comment by JeffreyAbbinante** [comment]
Use the version [here](https://github.com/microg/android_packages_apps_GmsCore/issues/638#issuecomment-428640487) and put it in /system/priv-app/ using the Systemizer Magisk Module. After that you will enable SafetyNet in the MicroG settings app and enable using the official server in the advanced settings. This is how I got SafetyNet to work on my phone. Hope this helps as it took me awhile to figure this out and resulted in me not wanting to use LineageOS for MicroG at first.

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19

**Comment by ale5000-git** [comment]
@Nanolx: Currently I can't do it on this repository.

**Comment by Atrashraccoon** [comment]
Sorry for that, my issue wasn't closed and I spent countless hours trying to educate myself on this matter, I'll be checking your link @Nanolx and close this issue.

**Comment by ale5000-git** [comment]
@Nanolx: Now, I can do it.
