### ISSUE TITLE
SafetyNet Issues

### ISSUE THREAD

**Issue by dylangerdaly** [microg/RemoteDroidGuard#31]
**Describe the bug**
Latest version of microG + RemoteDroidGuard isn't working.

```json
{"nonce":"","timestampMs":1635290903792,"ctsProfileMatch":false,"apkCertificateDigestSha256":[],"basicIntegrity":false,"advice":"RESTORE_TO_FACTORY_ROM","evaluationType":"BASIC"}
```

Both basic and CTS are returning `false`, I've successfully applied kdrag0n's AOSP patches listed [here](https://protonaosp.kdrag0n.dev/developers/details/safetynet), so the Build.Fingerprint etc APIs are indeed being hooked, as well as verifiedboot state.

It's at a point where both CTS and Basic should be passing successfully, is there a specific package name for DroidGuard? Currently I'm hooking calls to build flags if the package name is `org.microg.gms.droidguard` or `com.google.android.gms`.

This issue seems to be a specific issue with RemoteDroidGuard, standard GMS is reported to be working, does anyone know how this actually works? It looks like it's downloading an APK from somewhere then executing it?

Please advise.

**System**
Android 12

**Comment by ArchangeGabriel** [comment]
This has been broken for years, see https://github.com/microg/RemoteDroidGuard/issues/24, https://github.com/microg/RemoteDroidGuard/pull/29, https://github.com/microg/RemoteDroidGuard/pull/30. The last one in particular is wrongly closed, IIRC @0x5ECF4ULT was still trying to work on it.

**Comment by ArchangeGabriel** [comment]
And yes, RemoteDroidGuard is downloading the DroidGuard binary (not sure whether that’s an APK or not, it’s been years since I last looked into this), and executing it in a partial sandbox.

**Comment by 0x5ECF4ULT** [comment]
@ArchangeGabriel Google changed some things again and SN is more broken than before. The certificate hashes array seems to get populated by the sandbox DG is executing code in. I'm trying to figure out why this doesn't happen but my reversing skills are not that great.

**Comment by ale5000-git** [comment]
Fixed with latest microG GmsCore.
