### ISSUE TITLE
SafetyNet seems not to work.

### ISSUE THREAD

**Issue by jensMF** [microg/RemoteDroidGuard#4]
Since today SafetyNet has stopped working for me. I used superSu and xposed but now I wiped the whole phone (system, data, cach, dalvik) installed clean omnirom 6.0.1 and microG: Services Core, Services Framework, DroidGuardHelper an BlankStore. In SafetyNet Helper I now get:
Response signature validation: error

Error Msg:
Response signature validation error: https://www.googleapis.com/androidcheck/v1/attestations/veryfie?key=AlzaSyATMqwT6E0ndqZa43uQNhFOWjQi9RoVQlc

**Comment by julianwi** [comment]
This also happens on my device sometimes. But that is not problematic, because it does only affect SaftynetHelper app. You can still use normal apps like pokemon, while having this error.

**Comment by ArchangeGabriel** [comment]
Yes indeed, it’s only SafetyNet Helper that has this issue, I think there is some sort of rate limiting Google added to SafetyNet calls recently (because of all those PoGo root users and such trying tons of setups to get it working).

**Comment by jensMF** [comment]
Ok, thanks for your answers. Yesterday other SafetyNet-Apss I use (PoGo and Banking etc.) did not work either, but today everything is working again...
